main: com.winthier.protect.ProtectPlugin
name: Protect
version: 0.1
api-version: 1.19

description: Protect worlds from player modifications
author: StarTux
website: https://cavetale.com

depend: [Core, Area]

commands:

protect:
    description: Admin interface
    permission: protect.protect
    usage: /protect reload

permissions:

  protect.protect:
    description: Use /protect
    default: op

  protect.override:
    description: Override world protection
    default: op

  protect.farm:
    description: Use farm blocks
    default: op